kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: product-simple
spec:
  to:
    kind: Service
    name: product-simple
  port:
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: product-simple
  labels:
    app: product-simple
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: product-simple
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-simple
  labels:
    app: product-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-simple
  template:
    metadata:
      labels:
        app: product-simple
    spec:
      containers:
        - name: app
          image: image-registry.openshift-image-registry.svc:5000/base-data/product-simple
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: app
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 9779
              name: promethus
              protocol: TCP
          env:
          - name: TZ
            value: "Asia/Shanghai"
          - name: LANG
            value: en_US.UTF-8
          - name: JAVA_OPTS
            value: "-Dfile.encoding=UTF8"
          - name: AB_JOLOKIA_AUTH_OPENSHIFT
            value: 'true'
          - name: AB_JOLOKIA_OPTS
            value: 'useSslClientAuthentication=false,protocol=https'
          - name: 'AB_JOLOKIA_PASSWORD_RANDOM'
            value: 'false'
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
          volumeMounts:
          - name: data-volume
            mountPath: /deployments/data
      volumes:
      - name: data-volume
        configMap:
          name: product-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-data
data:
  data.json: |
    [
      {
        "id": "021-000263-00",
        "name": "LCD屏 TN 7 800*480 3.3V LVDS",
        "unitId": "EA",
        "unitName": "个",
        "factory": "1000"
      },
      {
        "id": "050-003160-02",
        "name": "FPC连接板",
        "unitId": "EA",
        "unitName": "个",
        "factory": "1000"
      },
      {
        "id": "030-001226-00",
        "name": "不锈钢内六角圆柱头组合螺钉 M6X16 钝化",
        "unitId": "EA",
        "unitName": "个",
        "factory": "1000"
      },
      {
        "id": "A90-000055---",
        "name": "高速长寿油脂MI-SETRAL-LI/PD1 5KG/EA(桶)",
        "unitId": "EA",
        "unitName": "个",
        "factory": "1000"
      },
      {
        "id": "0091-20-100431",
        "name": "电机轴延伸套",
        "unitId": "EA",
        "unitName": "个",
        "factory": "1008"
      },
      {
        "id": "120-022494-00",
        "name": "硬性光学内窥镜",
        "unitId": "EA",
        "unitName": "个",
        "factory": "1008"
      },
      {
        "id": "021-000389-00",
        "name": "27寸内窥显示器(迈瑞LOGO有底座)",
        "unitId": "EA",
        "unitName": "个",
        "factory": "1008"
      },
      {
        "id": "115-083519-00",
        "name": "大器械盒",
        "unitId": "EA",
        "unitName": "个",
        "factory": "1008"
      }
    ]
